import { AppDatabase } from "@thrico/database";
import { discussionCategory } from "@thrico/database";
import { v4 as uuidv4 } from "uuid";

export async function seedDiscussionCategories(
  db: AppDatabase,
  entityId: string,
  addedById: string
) {
  const categories = [
    {
      id: uuidv4(),
      name: "General",
      description: "General discussions",
      entity: entityId,
      slug: "general",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Announcements",
      description: "Official announcements",
      entity: entityId,
      slug: "announcements",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Technology",
      description: "Tech news and discussions",
      entity: entityId,
      slug: "technology",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Science",
      description: "Science topics and discoveries",
      entity: entityId,
      slug: "science",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Health",
      description: "Health and wellness",
      entity: entityId,
      slug: "health",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Sports",
      description: "Sports news and discussions",
      entity: entityId,
      slug: "sports",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Movies",
      description: "Movie reviews and discussions",
      entity: entityId,
      slug: "movies",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Music",
      description: "Music and artists",
      entity: entityId,
      slug: "music",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Books",
      description: "Book recommendations and reviews",
      entity: entityId,
      slug: "books",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Travel",
      description: "Travel tips and experiences",
      entity: entityId,
      slug: "travel",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Food",
      description: "Food and recipes",
      entity: entityId,
      slug: "food",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Gaming",
      description: "Video games and board games",
      entity: entityId,
      slug: "gaming",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Education",
      description: "Learning and education",
      entity: entityId,
      slug: "education",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Career",
      description: "Jobs and career advice",
      entity: entityId,
      slug: "career",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Finance",
      description: "Personal finance and investing",
      entity: entityId,
      slug: "finance",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Parenting",
      description: "Parenting tips and support",
      entity: entityId,
      slug: "parenting",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Relationships",
      description: "Relationship advice",
      entity: entityId,
      slug: "relationships",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Fashion",
      description: "Fashion trends and advice",
      entity: entityId,
      slug: "fashion",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Art",
      description: "Art and creativity",
      entity: entityId,
      slug: "art",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Photography",
      description: "Photography tips and sharing",
      entity: entityId,
      slug: "photography",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Pets",
      description: "Pet care and stories",
      entity: entityId,
      slug: "pets",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Automotive",
      description: "Cars and vehicles",
      entity: entityId,
      slug: "automotive",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Home & Garden",
      description: "Home improvement and gardening",
      entity: entityId,
      slug: "home-garden",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "DIY",
      description: "Do it yourself projects",
      entity: entityId,
      slug: "diy",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Politics",
      description: "Political discussions",
      entity: entityId,
      slug: "politics",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "History",
      description: "History and events",
      entity: entityId,
      slug: "history",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Philosophy",
      description: "Philosophical discussions",
      entity: entityId,
      slug: "philosophy",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Religion",
      description: "Religion and spirituality",
      entity: entityId,
      slug: "religion",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Environment",
      description: "Environmental issues",
      entity: entityId,
      slug: "environment",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Coding",
      description: "Programming and coding",
      entity: entityId,
      slug: "coding",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Startups",
      description: "Startup advice and stories",
      entity: entityId,
      slug: "startups",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Business",
      description: "Business and entrepreneurship",
      entity: entityId,
      slug: "business",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Marketing",
      description: "Marketing tips and trends",
      entity: entityId,
      slug: "marketing",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Legal",
      description: "Legal advice and discussions",
      entity: entityId,
      slug: "legal",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Mental Health",
      description: "Mental health support",
      entity: entityId,
      slug: "mental-health",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Fitness",
      description: "Fitness and exercise",
      entity: entityId,
      slug: "fitness",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Yoga",
      description: "Yoga and meditation",
      entity: entityId,
      slug: "yoga",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Language Learning",
      description: "Learning new languages",
      entity: entityId,
      slug: "language-learning",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Coding Challenges",
      description: "Programming challenges",
      entity: entityId,
      slug: "coding-challenges",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Web Development",
      description: "Web development topics",
      entity: entityId,
      slug: "web-development",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Mobile Development",
      description: "Mobile app development",
      entity: entityId,
      slug: "mobile-development",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Cloud Computing",
      description: "Cloud services and discussions",
      entity: entityId,
      slug: "cloud-computing",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "AI & Machine Learning",
      description: "Artificial intelligence topics",
      entity: entityId,
      slug: "ai-machine-learning",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Blockchain",
      description: "Blockchain and crypto",
      entity: entityId,
      slug: "blockchain",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Data Science",
      description: "Data science and analytics",
      entity: entityId,
      slug: "data-science",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Hardware",
      description: "Computer hardware",
      entity: entityId,
      slug: "hardware",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Security",
      description: "Cybersecurity topics",
      entity: entityId,
      slug: "security",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Open Source",
      description: "Open source projects",
      entity: entityId,
      slug: "open-source",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Events",
      description: "Upcoming events",
      entity: entityId,
      slug: "events",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Suggestions",
      description: "Suggestions and feedback",
      entity: entityId,
      slug: "suggestions",
      addedBy: addedById,
    },
    {
      id: uuidv4(),
      name: "Support",
      description: "Get help and support",
      entity: entityId,
      slug: "support",
      addedBy: addedById,
    },
    // Add more categories as needed
  ];

  for (const category of categories) {
    await db.insert(discussionCategory).values(category);
  }

  console.log("Discussion categories seeded!");
}
