export const BUILT_IN_TEMPLATES = [
  {
    name: "New Member Welcome",
    slug: "new-member-welcome",
    subject: "Welcome to {{entity_name}}!",
    json: JSON.stringify([
      {
        id: "h1",
        type: "header",
        content: "",
        align: "center",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 14,
        color: "#1e293b",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "https://cdn.thrico.network/thrico.png",
        secondaryContent: "Community Hub",
      },
      {
        id: "he1",
        type: "heading",
        content: "Welcome to our Community! 🤝",
        align: "center",
        bold: true,
        italic: false,
        underline: false,
        fontSize: 32,
        color: "#1e293b",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "",
      },
      {
        id: "i1",
        type: "image",
        content:
          "https://images.unsplash.com/photo-1511632765486-a01980e01a18?q=80&w=1200",
        align: "center",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 14,
        color: "#1e293b",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "Community Members",
        logoUrl: "",
      },
      {
        id: "t1",
        type: "text",
        content:
          "We're thrilled to have you here! Our community is a space for innovators, creators, and leaders to connect and grow together. You've just unlocked access to our exclusive forums, events, and resources.",
        align: "center",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 15,
        color: "#475569",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "",
      },
      {
        id: "s1",
        type: "spacer",
        content: "",
        align: "left",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 14,
        color: "#1e293b",
        bgColor: "transparent",
        href: "",
        spacerSize: "sm",
        imageAlt: "",
        logoUrl: "",
      },
      {
        id: "b1",
        type: "button",
        content: "Complete Your Profile",
        align: "center",
        bold: true,
        italic: false,
        underline: false,
        fontSize: 14,
        color: "#ffffff",
        bgColor: "#6366f1",
        href: "https://thrico.network/onboarding",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "",
      },
      {
        id: "divider1",
        type: "divider",
        content: "",
        align: "left",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 14,
        color: "#1e293b",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "",
      },
      {
        id: "t2",
        type: "text",
        content:
          "Need help getting started? Check out our Getting Started guide or reply to this email to reach our support team.",
        align: "center",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 12,
        color: "#94a3b8",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "",
      },
      {
        id: "f1",
        type: "footer",
        content:
          "You are receiving this because you joined the Thrico Network community ecosystem. To manage your notification settings, please visit your dashboard preferences.",
        align: "center",
        bold: false,
        italic: false,
        underline: false,
        fontSize: 14,
        color: "#1e293b",
        bgColor: "transparent",
        href: "",
        spacerSize: "md",
        imageAlt: "",
        logoUrl: "",
      },
    ]),
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
        <h2 style="color: #333;">Welcome to the community!</h2>
        <p>Hi there,</p>
        <p>We are excited to have you as a new member of <strong>{{entity_name}}</strong>.</p>
        <p>You can now access all the features and connect with other members.</p>
        <div style="margin: 30px 0;">
          <a href="{{login_url}}" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold;">Login to your account</a>
        </div>
        <p>If you have any questions, feel free to reply to this email.</p>
        <p>Best regards,<br/>The {{entity_name}} Team</p>
      </div>
    `,
    isActive: true,
    isDeletable: false,
  },
];
